# Site settings
title: 'DanielBrice.net'
description: 'The personal website of Daniel Brice'
baseurl: ''
url: 'http://www.danielbrice.net'
include: [ '_courses' ]

# Author settings
email: 'danielbrice@gmail.com'
twitter_username: 'fried_brice'
github_username:  'friedbrice'
stackex_username: '2387766'

# Build settings
markdown: 'kramdown'
exclude: [ 'README.md', 'Gemfile' ]
# debug: 'true' # comment this out before production
