# Site settings
title: 'DanielBrice.net'
description: |
  The personal website of Daniel Brice, PhD.
  Copyright 2014 Daniel Brice
  [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
baseurl: ''
url: 'http://www.danielbrice.net'
collections: [ 'keys' ]

# Author settings
email: 'danielbrice@gmail.com'
twitter_username: 'fried_brice'
github_username:  'friedbrice'
stackex_username: '2387766/fried-brice'

# Build settings
markdown: 'kramdown'
exclude: [ 'README.md', 'Gemfile' ]
debug: 'true' # comment this out before production

