# Site settings
title: 'DanielBrice.net'
description: 'The personal website of Daniel Brice, PhD'
baseurl: ''
url: 'http://www.danielbrice.net'
include: [ '_courses', '_pages' ]

# Author settings
email: 'danielbrice@gmail.com'
twitter_username: 'fried_brice'
github_username:  'friedbrice'
stackex_username: '2387766'

# Build settings
markdown: 'kramdown'
exclude: [ 'README.md', 'Gemfile', 'Gemfile.lock' ]
plugins: [ 'jekyll-redirect-from' ]
whitelist: [ 'jekyll-redirect-from' ]
# debug: 'true' # comment this out before production
