# Site settings
title: 'DanielBrice.net'
description: 'The personal website of Daniel Brice, PhD'
baseurl: ''
url: 'http://www.danielbrice.net'
include: [ '_courses', '_pages' ]

# Author settings
email: 'danielbrice@gmail.com'
twitter_username: '_fried_brice_'
github_username:  'friedbrice'
stackex_username: '2387766'

# Build settings
markdown: 'kramdown'
exclude:
  - '.bundle'
  - '.DS_Store'
  - '.gems'
  - '.github'
  - '.gitignore'
  - '.sass-cache'
  - 'Gemfile.lock'
  - 'Gemfile'
  - 'Makefile'
  - 'README.md'
  - 'vendor'
plugins: [ 'jekyll-redirect-from' ]
whitelist: [ 'jekyll-redirect-from' ]
excerpt_separator: "<!-- break -->"
