source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-redirect-from'
gem 'webrick'
gem 'nokogiri'

# Filter gems (https://github.com/gjtorikian/html-pipeline#dependencies)
# gem 'commonmarker'
# gem 'email_reply_parser'
# gem 'escape_utils'
# gem 'gemoji'
# gem 'RedCloth'
# gem 'rinku'
# gem 'rouge'
# gem 'sanitize'
