name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0
      - name: Configure Pages
        id: configure_pages
        uses: actions/configure-pages@v5
      - name: Check Outputs from Configure Pages
        run: |
          echo "${steps.configure_pages.outputs.base_url}"
          echo "${steps.configure_pages.outputs.origin}"
          echo "${steps.configure_pages.outputs.host}"
          echo "${steps.configure_pages.outputs.base_path}"
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --source "${{ steps.configure_pages.outputs.base_path }}" --baseurl "${{ steps.configure_pages.outputs.base_url }}"
          ls -lR ./_site/
        env:
          JEKYLL_ENV: production
      - name: Upload Pages Artifact
        id: upload_pages_artifact
        uses: actions/upload-pages-artifact@v3
      - name: Check Outputs from Upload Pages Artifact
        run: |
          echo "${steps.upload_pages_artifact.outputs.artifact_id}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Pages
        id: deploy_pages
        uses: actions/deploy-pages@v4
      - name: Check Outputs from Deploy Pages
        run: |
          echo ${{ steps.deploy_pages.outputs.page_url }}
